---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: bggdb-mysql
  labels: 
    name: bggdb-mysql
spec: 
  replica: 2
  secretName: bgg-secret

  image: chukmunnlee/bggdb:v1
  mysqlVersion: "5.7"

  persistentVolumeClaim:
    storageClassName: do-block-storage
    accessModes: 
    - ReadWriteOnce
    resources:
    requests:
      storage: 1Gi
