---
apiVersion: v1
kind: ConfigMap
metadata:
   name: wordpress-cm
   labels:
      name: wordpress-cm
data:
   WORDPRESS_DB_HOST: wordpress-svc.wns.svc.cluster.local
   WORDPRESS_DB_USER: user1
   WORDPRESS_DB_PASSWORD: root

