---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    name: bggdb-deploy

spec:
  replicas: 1
  selector: 
    matchLabels:
      name: bggdb-pod
  template:
    metadata:
      name: bggdb-pod
      labels:
        name: bggdb-pod
    spec:
      containers:
      - name: bggdb-container
        image: lcl1/my_bgg:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc

spec:
  type: ClusterIP
  selector: 
    name: bggdb-pod
  ports:
  - port: 3306
    targetPort: 3306
