---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  labels:
    name: fortune-pod

spec:
  containers:
  - name: fortune-container
    image: lcl1/my_fortune:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000